bot:
  check:
    initialDelay: 60000
    fixedDelay: 60000
  scope: app_mentions:read,chat:write,commands,chat:write.customize
  oauth:
    installPath: /slack/install
    redirectUriPath: /slack/oauth_redirect
    completionUrl: "OAUTH_COMPLETION_URL"
    cancellationUrl: "OAUTH_CANCELLATION_URL"
  credentials:
    botToken: "BOT_TOKEN"
    signingSecret: "SIGNING_SECRET"
    clientId: "CLIENT_ID"
    clientSecret: "CLIENT_SECRET"
  rootDir: my_path_here

notifications:
  max: 10

foreman:
  baseUrl: https://dashboard.foreman.mn
  apiUrl: https://api.foreman.mn

server:
  port: 3000
  ssl.enabled-protocols: TLSv1.3, TLSv1.2

logging:
  level:
    root: debug