bot:
  check:
    initialDelay: 60000
    fixedDelay: 60000
  scope: app_mentions:read,chat:write,commands,chat:write.customize
  oauth:
    installPath: /slack/install
    redirectUriPath: /slack/oauth_redirect
    completionUrl: "OAUTH_COMPLETION_URL"
  credentials:
    botToken: "BOT_TOKEN"
    signingSecret: "SIGNING_SECRET"
    clientId: "CLIENT_ID"
    clientSecret: "CLIENT_SECRET"

notifications:
  max: 10

foreman:
  baseUrl: https://dashboard.foreman.mn
  apiUrl: https://api.foreman.mn

server:
  port: 3000

logging:
  level:
    root: debug